language: python
dist: xenial
os: linux
python:
- '3.8'

install:
- pip install coveralls
- pip install pyorient_native
- "./ci/start-ci.sh $ORIENTDB_VERSION"

cache:
  directories:
  - ./ci/environment/
  - ./docs/build/html/
  - "./ci/environment/"

script:
- nosetests -vv --with-coverage --cover-xml --cover-erase --cover-package=pyorient

before_cache:
- ls -la ./ci/environment/
- rm -f ./ci/environment/orientdb-community-$ORIENTDB_VERSION/log/*
- rm -rf ./ci/environment/orientdb-community-$ORIENTDB_VERSION/databases/*

after_success:
  - coveralls
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "develop" && ./docs/publish.sh

branches:
  except:
    - gh-pages

env:
  jobs:
    - ORIENTDB_VERSION=3.2.0
  global:
    - secure: "FfqHFu2i1X5dIqzIxIGraEZrGSswSE4XVR7Ig9fkfYhbQfhFfZCOaRG95tyoZW7g5S0K2Kiw/oDyIKMPC+5g5PfMv2uvI/LZtokOy5ZewF0SHMjuCA54P+y83uindQMfb6KvPc9h/6tV2eogQGZ1y+juXteb4NRDUxt27NppRwM="
